# version: "3"
# services:
#   backend:
#     build: ./backend # specify where the Dockerfile is
#     ports:
#       - "3001:3001" # [HOST_PORT]:[CONTAINER_PORT]


#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         REACT_APP_BACKEND_URL: http://backend:3001 # <- within docker compose you can call a container with it's service name
#     ports:
#       - "3002:8000"
#     depends_on:
#       - backend

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"  # Expose only nginx port
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - frontend
#       - backend

version: "3"
services:
  backend:
    build: ./backend
    # No direct port exposure in production
    environment:
      - CORS_ORIGIN=http://localhost

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: /api  # Use relative path for production
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Only expose nginx port
    volumes:
      - type: bind
        source: ${PWD}/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend