services:
  backend:
    build: ./backend
    # No direct port exposure in production
    environment:
      - CORS_ORIGIN=http://localhost
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: /api  # Use relative path for production
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Only expose nginx port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

