version: "3"
services:
  backend:
    build: ./backend # specify where the Dockerfile is
    ports:
      - "3001:3001" # [HOST_PORT]:[CONTAINER_PORT]
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://127.0.0.1:3001 # <- within docker compose you can call a container with it's service name
    ports:
      - "8000:8000"
    depends_on:
      - backend
