version: "3"
services:
  backend:
    build: ./backend # specify where the Dockerfile is
    ports:
      - "3001:3001" # [HOST_PORT]:[CONTAINER_PORT]
      - "5678:5678" # Debugger port

  frontend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - backend
